// src/app/juno60/juno60.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-juno60',
  templateUrl: './juno60.component.html',
  styleUrls: ['./juno60.component.css']
})
export class Juno60Component implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<h1>Roland JUNO-60 Editor</h1>
<table>
    <tr>
        <th>LFO</th>
        <th>DCO</th>
        <th>HPF</th>
        <th>VCF</th>
        <th>VCA</th>
        <th>ENV</th>
        <th>CHORUS</th>
    </tr>
    <tr>
        <td>
            <mat-slider vertical min="1" max="10" step="1" value="0"></mat-slider>
            <mat-slider vertical min="1" max="10" step="1" value="0"></mat-slider>
        </td>
    </tr>
</table>

// src/components/Juno60.tsx
import React from 'react';
import './Juno60.css'
import Lfo from './Lfo';
import Dco from './Dco';
import Hpf from './Hpf';
import Vcf from './Vcf';
import Vca from './Vca';
import Env from './Env';
import Chorus from './Chorus';

const Juno60: React.FC = () =>  {
    return(
        <div className="main">
            <h1>Roland JUNO-60 Editor</h1>
            <table className="board-comp">
                <thead>
                    <tr>
                        <th>LFO</th>
                        <th>DCO</th>
                        <th>HPF</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        {/*LFO contents*/}
                        <td className="board-comp">
                            <Lfo onChange={state => console.log(state)} />
                        </td>
                        {/* DCO contents */}
                        <td className="board-comp">
                            <Dco onChange={state => console.log(state)}/>
                        </td>
                        {/* HPF contents */}
                        <td className="board-comp">
                            <Hpf />
                        </td>
                    </tr>
                </tbody>
            </table>
            <br/>
            <table className="board-comp">
                <thead>
                    <tr>
                        <th>VCF</th>
                        <th>VCA</th>
                        <th>ENV</th>
                        <th>CHORUS</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        {/* VCF contents */}
                        <td className="board-comp">
                            <Vcf />
                        </td>
                        {/* VCA contents */}
                        <td className="board-comp">
                            <Vca />
                        </td>
                        {/* ENV contents */}
                        <td className="board-comp">
                            <Env />
                        </td>
                        {/* CHORUS contents */}
                        <td className="chorus">
                            <Chorus />
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    )
}

export default Juno60;
